// Generated by CoffeeScript 1.6.3
(function() {
  var Dog, dog;

  Dog = (function() {
    function Dog(name) {
      this.name = name;
    }

    Dog.prototype.growl = function() {
      return console.log("" + this.name + " is Growling");
    };

    return Dog;

  })();

  dog = new Dog("Rusty");

  dog.growl();

  $(function() {
    var dropdown, menu;
    menu = $('#menu');
    dropdown = $('#dropdown');
    dropdown.hide();
    menu.on('mouseover', function(e) {
      return dropdown.stop().show(200);
    });
    return menu.on('mouseover', function(e) {
      return dropdown.stop().show(200);
    });
  });

}).call(this);
